ocial/ocial_project/ocial/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from topics import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name= 'home'),
	path('accounts/', include('accounts.urls')),
    path('classroom/', include('topics.urls')),
    path('topics',views.topics, name= 'topics'),
    path('news',views.news, name= 'news'),
    path('<username>/', views.userprofile, name='userprofile'),
    path('<username>/followers', views.userfollowers, name='userfollowers'),
    path('<username>/following', views.userfollowing, name='userfollowing'),
    path('follow/<username>/', views.followuser, name='followuser'),
    path('unfollow/<username>/', views.unfollowuser, name='unfollowuser'),
    path('editprofile',views.editprofile, name= 'editprofile'),
    path('editprofile/changepassword',views.changepassword, name= 'changepassword'),
    path('explore',views.explore, name= 'explore'),
    path('exploretopic/<int:topic_id>',views.exploretopic, name= 'exploretopic'),
    path('exploreteacher/<id>',views.exploreteacher, name= 'exploreteacher'),
    path('course/<int:course_id>/', views.coursedetail, name = 'coursedetail'),
    path('enroll/<int:course_id>', views.enrollcourse , name='enrollcourse'),
    url('recommendation/', include('recommendation.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ocial/ocial_project/topics/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('',views.classroom, name= 'classroom'),
    path('coursestatistics/<int:course_id>/',views.coursestatistics, name= 'coursestatistics'),
    path('sectionstatistics/<int:section_id>/',views.sectionstatistics, name= 'sectionstatistics'),
    path('teacher',views.teacher, name= 'teacher'),
	path('newcourse',views.newcourse, name= 'newcourse'),
	path('editcourse/<int:course_id>/', views.editcourse, name = 'editcourse'),
	path('editcourse/<int:course_id>/glossary/', views.glossary, name = 'glossary'),
	path('editsection/<int:section_id>/', views.editsection, name = 'editsection'),
	path('editlecture/<int:lecture_id>/', views.editlecture, name = 'editlecture'),
	path('editquiz/<int:quiz_id>/', views.editquiz, name = 'editquiz'),
    path('editquestion/<int:question_id>/', views.editquestion, name = 'editquestion'),
	path('deletecourse/<int:course_id>/', views.deletecourse, name = 'deletecourse'),
    path('deletesection/<int:section_id>/', views.deletesection, name = 'deletesection'),
    path('deleteresource/<int:resource_id>/', views.deleteresource, name = 'deleteresource'),
    path('deletelecture/<int:lecture_id>/', views.deletelecture, name = 'deletelecture'),
    path('deletequiz/<int:quiz_id>/', views.deletequiz, name = 'deletequiz'),
    path('deletequestion/<int:question_id>/', views.deletequestion, name = 'deletequestion'),
    path('deletechoice/<int:choice_id>/', views.deletechoice, name = 'deletechoice'),
    path('deleteglossary/<int:glossary_id>/', views.deleteglossary, name = 'deleteglossary'),
    path('newglossary/<int:course_id>/<str:wiki_id>', views.newglossary, name = 'newglossary'),
    path('learner',views.learner, name= 'learner'),
    path('viewcourse/<int:course_id>', views.viewcourse, name = 'viewcourse'),
    path('viewcourse/<int:course_id>/glossary/', views.viewglossary, name = 'viewglossary'),
    path('viewsection/<int:section_id>/', views.viewsection, name = 'viewsection'),
    path('viewlecture/<int:lecture_id>/', views.viewlecture, name = 'viewlecture'),
    path('viewquiz/<int:quiz_id>/', views.viewquiz, name = 'viewquiz'),
    path('unenroll/<int:course_id>/', views.unenrollcourse, name = 'unenrollcourse'),



]

ocial/ocial_project/topics/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Count
from accounts.models import *
import requests
import json



class Topic(models.Model):
	title = models.CharField(max_length=200,unique=True)

	def __str__(self):
		return self.title

class Course(models.Model):
	title = models.CharField(max_length=200,blank=False)
	pubdate = models. DateTimeField()
	image = models.ImageField(upload_to='images/', default= '../static/default.jpg')
	description = models.TextField(blank=True)
	wywl = models.TextField(blank=True)
	teacher = models.ForeignKey(User, on_delete=models.CASCADE)
	topic = models.ForeignKey('Topic', on_delete=models.CASCADE)
	published = models.BooleanField(default=False)
	course_learner = models.ManyToManyField(Learner, blank=True,through='Learner_Course_Record')
	isPublishable = models.BooleanField(default=False)
	completeRate = models.DecimalField(default= 0,max_digits=5,decimal_places=1)
	numberofLearners = models.IntegerField(default= 0)



	def pub_date_exact(self):
		return self.pubdate.strftime('%e %B %Y %H:%M')


	def pub_date(self):
		return self.pubdate.strftime('%e %B %Y')

	def __str__(self):
		return self.title

	def summary(self):
		return self.description[:200]

class Learner_Course_Record(models.Model):
	learner = models.ForeignKey(Learner, on_delete=models.CASCADE)
	course = models.ForeignKey(Course, on_delete=models.CASCADE)
	isFinished = models.BooleanField(default=False)
	completeRate = models.DecimalField(default= 0, max_digits=5,decimal_places=1)

	def __str__(self):
		return self.learner.user.username + " - " +self.course.title

class Glossary(models.Model):
	identifier=models.CharField(max_length=32,default="")
	name = models.CharField(max_length=200)
	image_url = models.CharField(max_length=1000, blank=True)
	description = models.TextField(blank=True)
	url = models.CharField(max_length=1000, blank=True)
	course = models.ForeignKey('Course', on_delete=models.CASCADE)


	def __str__(self):
		return self.name

class Section(models.Model):
	name = models.CharField(max_length=200)
	course = models.ForeignKey('Course', on_delete=models.CASCADE)
	order =  models.IntegerField(default=1)
	description = models.TextField(blank=True)
	section_learner = models.ManyToManyField(Learner, blank=True,through='Learner_Section_Record')
	isLinked = models.BooleanField(default=False)
	isPublishable = models.BooleanField(default=False)
	completeRate = models.DecimalField(default= 0, max_digits=5,decimal_places=1)



	class Meta:
		ordering = ['order']

	def __str__(self):
		return self.name

class Learner_Section_Record(models.Model):
	learner = models.ForeignKey(Learner, on_delete=models.CASCADE)
	section = models.ForeignKey(Section, on_delete=models.CASCADE)
	isFinished = models.BooleanField(default=False)
	completeRate = models.DecimalField(default= 0, max_digits=5,decimal_places=1)

	def __str__(self):
		return self.learner.user.username + " - " +self.section.name

class Lecture(models.Model):
	title = models.CharField(max_length=200)
	body = models.TextField(blank=True)
	section = models.ForeignKey('Section', on_delete=models.CASCADE)
	order =  models.IntegerField(default=1)
	lecture_learner = models.ManyToManyField(Learner, blank=True,through='Learner_Lecture_Record')
	completeRate = models.DecimalField(default= 0, max_digits=5,decimal_places=1)



	class Meta:
		ordering = ['order']
		verbose_name = 'Lecture'

	def __str__(self):
		return self.title

class Learner_Lecture_Record(models.Model):
	learner = models.ForeignKey(Learner, on_delete=models.CASCADE)
	lecture = models.ForeignKey(Lecture, on_delete=models.CASCADE)
	isFinished = models.BooleanField(default=False)

	def __str__(self):
		return self.learner.user.username + " - " +self.lecture.title

class Quiz(models.Model):
	title = models.CharField(max_length=200)
	section = models.ForeignKey('Section', on_delete=models.CASCADE)
	order =  models.IntegerField(default=1)
	successrate =  models.IntegerField(default=0)
	quiz_learner = models.ManyToManyField(Learner, blank=True,through='Learner_Quiz_Record')
	isPublishable = models.BooleanField(default=False)
	completeRate = models.DecimalField(default= 0, max_digits=5,decimal_places=1)



	class Meta:
		ordering = ['order']
		verbose_name = 'Quiz'

	def __str__(self):
		return self.title

class Learner_Quiz_Record(models.Model):
	learner = models.ForeignKey(Learner, on_delete=models.CASCADE)
	quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
	isFinished = models.BooleanField(default=False)

	def __str__(self):
		return self.learner.user.username + " - " +self.quiz.title

class Question(models.Model):
	title = models.TextField(blank=True)
	quiz = models.ForeignKey('Quiz', on_delete=models.CASCADE)
	order =  models.IntegerField(default=1)
	isPublishable = models.BooleanField(default=False)


	class Meta:
		ordering = ['order']
		verbose_name = 'Question'

	def __str__(self):
		return self.title

class Choice(models.Model):
	title = models.TextField(blank=True)
	question = models.ForeignKey('Question', on_delete=models.CASCADE)
	order =  models.IntegerField(default=1)
	isTrue = models.BooleanField(default=False)


	class Meta:
		ordering = ['order']
		verbose_name = 'Choice'

	def __str__(self):
		return self.title

class Resource(models.Model):
	name = models.CharField(max_length=200, blank=True)
	link = models.FileField(upload_to='sources/', blank=True)
	section = models.ForeignKey('Section', on_delete=models.CASCADE)


	def __str__(self):
		return self.name

class ActivityStream_JSON(models.Model):
	context = models.CharField(max_length=200, blank=True)
	summary = models.CharField(max_length=200, blank=True)
	type = models.CharField(max_length=200, blank=True)
	actor = models.CharField(max_length=200, blank=True)
	object = models.CharField(max_length=200, blank=True)
	published = models.CharField(max_length=200, blank=True)
	imgUrl = models.CharField(max_length=200, blank=True)
	keysArray = ['@context', 'summary', 'type', 'actor', 'object', 'published']



	def check_validity(self,json_data):

		for key in self.keysArray:
			if not key in json_data:
				return False

		self.summary = json_data['summary']
		self.type = json_data['type']
		self.actor = json_data['actor']
		self.object =  json_data['object']
		self.published =  json_data['published']

		return True

	def get_object(self):
		return self

activityHost = "http://activity_stream:3000/"
class GetActivityStream(models.Model):

	def getFollowedActivities(self,request):
		userprofile = UserProfile.objects.get(user=request.user)
		following_q = userprofile.user.following.all()
		responses = list()
		json_datas = list()
		print("current")
		for usr in following_q:
			r = requests.get(activityHost + "getAllActivities?actor=" + request._current_scheme_host + "/" + usr.following.username+"/")
			responses.append(r)

		json_datas = self.convertToJson(responses)

		return self.checkValidity(json_datas)


	def getMyActivities(self,request):
		responses = list()
		json_datas = list()
		r = requests.get(activityHost + "getAllActivities?actor=" + request._current_scheme_host + "/" + request.user.username+"/")
		responses.append(r)
		json_datas = self.convertToJson(responses)
		return self.checkValidity(json_datas)

	def getActivitiesProfile(self,request,username):
		responses = list()
		json_datas = list()
		r = requests.get(activityHost + "getAllActivities?actor=" + request._current_scheme_host + "/" + username + "/")
		responses.append(r)
		json_datas = self.convertToJson(responses)
		return self.checkValidity(json_datas)

	def getPeopleThatFollowMe(self,request):
		responses = list()
		json_datas = list()
		r = requests.get(activityHost + "getAllActivities?object=" + request._current_scheme_host + "/" + request.user.username)
		responses.append(r)
		json_datas = self.convertToJson(responses)
		return self.checkValidity(json_datas)


	def checkValidity(self,data_list):
		valid_jsons = list()
		for json_data_ in data_list:
			data = json.loads(json_data_)
			test = ActivityStream_JSON()
			isValid = test.check_validity(data)
			if isValid:
				valid_jsons.append(test.get_object())
		return valid_jsons

	def convertToJson(self,data_list):
		print("following : ")
		json_datas = list()
		for res in data_list:
			res = res.json()

			if res is not None:
				for r in res:
					json_datas.append(json.dumps(res.get(r)))
					#print("aaaa" + json.dumps(res.get(r)))
		return json_datas

ocial/ocial_project/topics/templates/topics/editquiz.html
{% extends '../temp/classroom_base.html' %} {% load static %} {% load my_tags %} {% block content %}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/RubaXa/Sortable/Sortable.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>

<script src="https://unpkg.com/web-animations-js@2.3.1/web-animations.min.js"></script>
<script src="https://unpkg.com/hammerjs@2.0.8/hammer.min.js"></script>
<script src="https://unpkg.com/muuri@0.7.1/dist/muuri.min.js"></script>

<style type="text/css">
    .grid {
        position: relative;
    }
    
    .item {
        display: block;
        position: absolute;
        width: 100%;
        z-index: 1;
        padding: 10px 15px;
        margin-bottom: -1px;
        background-color: #fff;
        border: 1px solid #ddd
    }
    
    .item.muuri-item-dragging {
        z-index: 3;
    }
    
    .item.muuri-item-releasing {
        z-index: 2;
    }
    
    .item.muuri-item-hidden {
        z-index: 0;
    }
    
    .item-content {
        position: relative;
        width: 100%;
        height: 100%;
    }
</style>

<div class="container-fluid" style="margin-top:40px;">

    {% if error %}

    <div class="alert alert-danger" role="alert">
        {{error}} </div>
    {%endif%}

    <form method="POST" action="{% url 'editquiz' quiz.id %}" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-group">

            <div class="row">
                <div class="col-sm-8">

                    {% if quiz.id %}
                    <small>

                    <ul class="breadcrumb">

                      <li>{{quiz.section.course.topic}}</a> <span class="divider">/ &nbsp</span></li>
                      <li>{{quiz.section.course}}</a> <span class="divider">/&nbsp</span></li>
                      <li>{{quiz.section}}</a> <span class="divider">/&nbsp</span></li>

                    </ul>                            </small> {% endif %} {%if quiz.isPublishable == False%}
                    <div class="alert alert-danger" role="alert">

                        <small>Notice: In order to submit this quiz it must have at least one question and all questions must have green check(submitted) marks.</small> </div>
                    {%endif%}
                    <input type="text" class="form-control" name="quiztitle" placeholder="Quiz Title (Required)" value="{{ quiz.title }}">

                    <input type="hidden" name="question-order" id="question-order">

                    <ul class="list-group mt-4" id="demo2">
                        <div class="modal fade" id="questionModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">New Question</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <form>
                                            <div class="form-group">
                                                <textarea type="text" class="form-control" name="questiontitle" placeholder="Question (Required)" rows=4></textarea>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-dark" data-dismiss="modal">Close</button>
                                        <button type="submit" name="newquestion" class="btn btn-danger"><i class="fas fa-question"></i> New Question</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <button type="button" class="btn btn-danger btn-block" data-toggle="modal" data-target="#questionModal" data-whatever="@getbootstrap"><i class="fas fa-question"></i> New Question</button>

                        <ul class="grid">

                            {% for question in quiz.question_set.all %}
                            <li class="item" data-id={{question.id}}><a href="{% url 'editquestion' question.id %}">Question {{question.order}}: {{question.title}}</a> {%if question.isPublishable == True%}
                                <i class="fas fa-check" style="color:green;"></i> {%endif%}

                                <button style="float: right;" type="button" onclick="window.location.href='{% url 'deletequestion' question.id %}';" class="btn btn-pill btn-outline-dark"><i class="far fa-trash-alt"></i></button>

                            </li>

                            {% endfor %}
                        </ul>
                    </ul>

                </div>

                <div class="col-sm-4">

                    <br />
                    <div class="form-inline">

                        <div class="form-group ">
                            Passing Score:</div>
                        <div class="form-group ">

                            <input type="number" class="form-control" name="quizsuccessrate" min="0" max="100" value="{{quiz.successrate}}">%
                        </div>
                    </div>

                    <br />

                    <button type="submit" name="save_quiz" id="save_quiz" class="btn btn-outline-dark btn-block"><i class="far fa-save"></i> Save</button>

                    {% if quiz.id %} {%if quiz.isPublishable == True%}

                    <button type="submit" name="submit_quiz" id="submit_quiz" class="btn btn-danger btn-block">Submit</button>

                    {%else%}

                    <button type="submit" name="save_exit_quiz" id="save_exit_quiz" class="btn btn-outline-dark btn-block">Save and Exit</button>

                    {%endif%}

                    <button style="float: right;" type="button" onclick="window.location.href='{% url 'deletequiz' quiz.id %}';" class="btn btn-block btn-outline-dark" style="margin-bottom: 5px;"><i class="far fa-trash-alt"></i> Delete Quiz</button>

                    {% endif %}

                </div>
            </div>

        </div>

    </form>

    <script type="text/javascript">
        var grid = new Muuri('.grid', {
            dragEnabled: true,
            dragAxis: 'y'
        });

        document.getElementById("save_quiz").onclick = function() {
            sendQuestionOrder()
        };

        document.getElementById("submit_quiz").onclick = function() {
            sendQuestionOrder()
        };

        function sendQuestionOrder() {

            var questionorder = document.getElementById("question-order");
            questionorder.value = grid.getItems().map(item => item.getElement().getAttribute('data-id'));
            questionorder.form.submit();

        }
    </script>

    <script type="text/javascript">
        document.getElementById("save_exit_quiz").onclick = function() {
            sendQuestionOrder()
        };
    </script>

</div>

{%endblock%}

ocial/ocial_project/topics/templates/topics/editsection.html
{% extends '../temp/classroom_base.html' %} {% load static %} {% load my_tags %} {% block content %}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/RubaXa/Sortable/Sortable.min.js"></script>

<style type="text/css">
    .grid {
        position: relative;
    }
    
    .item {
        display: block;
        position: absolute;
        width: 100%;
        z-index: 1;
        padding: 10px 15px;
        margin-bottom: -1px;
        background-color: #fff;
        border: 1px solid #ddd
    }
    
    .item.muuri-item-dragging {
        z-index: 3;
    }
    
    .item.muuri-item-releasing {
        z-index: 2;
    }
    
    .item.muuri-item-hidden {
        z-index: 0;
    }
    
    .item-content {
        position: relative;
        width: 100%;
        height: 100%;
    }
</style>

<div class="container-fluid" style="margin-top:40px;">

    {% if error %}

    <div class="alert alert-danger" role="alert">
        {{error}} </div>
    {%endif%}

    <form method="POST" action="{% url 'editsection' section.id %}" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-group">

            <div class="row">
                <div class="col-sm-8">
                    {% if section.id %}
                    <small>

                    <ul class="breadcrumb">

                      <li>{{section.course.topic}}</a> <span class="divider">/ &nbsp</span></li>
                      <li>{{section.course}}</a> <span class="divider">/&nbsp</span></li>

                    </ul>
                                        </small> {% endif %} {%if section.isPublishable == False%}
                    <div class="alert alert-danger" role="alert">

                        <small>Notice: In order to submit this section it must have at least one lecture/quiz and all lectures/quizzes must have green check(submitted) marks.</small> </div>
                    {%endif%}

                    <input type="text" class="form-control" name="sectionname" placeholder="Section Name (Required)" value="{{ section.name }}">

                    <br />

                    <textarea type="text" class="form-control" name="sectiondescription" rows="4" placeholder="Section Description">{{ section.description }}</textarea>

                    <div class="modal fade" id="lectureModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">New Learning Path Item</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <form>
                                        <div class="form-group">
                                            <input type="text" class="form-control" name="itemtitle" placeholder="Title (Required)">
                                        </div>
                                    </form>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-dark " data-dismiss="modal">Close</button>
                                    <button type="submit" name="newquiz" class="btn btn-danger "><i class="fas fa-question"></i> New Quiz </button>
                                    <button type="submit" name="newlecture" class="btn btn-danger "><i class="fas fa-chalkboard-teacher"></i> New Lecture</button>
                                </div>
                            </div>
                        </div>
                    </div>

                    {%if section.isLinked == True%}
                    <input type="checkbox" name="sectionislinked" value="True" checked> Linked Section {% elif section.isLinked == False%}
                    <input type="checkbox" name="sectionislinked" value="True"> Linked Section {% endif %}
                    <br />
                    <br />

                    <button type="button" class="btn btn-danger btn-block" data-toggle="modal" data-target="#lectureModal" data-whatever="@getbootstrap"><i class="fas fa-plus"></i> Add Quiz/Lecture</button>

                    <input type="hidden" name="lp-order" id="lp-order">

                    <ul class="grid">

                        {% for pathitem in learningpath %} {%if pathitem|verbose_name == "Lecture" %}

                        <li class="item" data-id={{pathitem|verbose_name}}:{{pathitem.id}}><a href="{% url 'editlecture' pathitem.id%}">{{pathitem.order}}. {{pathitem|verbose_name}}: {{pathitem.title}}</a>

                            <i class="fas fa-check" style="color:green;"></i>

                            <button style="float: right;" type="button" onclick="window.location.href='{% url 'deletelecture' pathitem.id %}';" class="btn btn-pill btn-outline-default"><i class="far fa-trash-alt"></i></button>

                            {%else%}

                            <li class="item" data-id={{pathitem|verbose_name}}:{{pathitem.id}}><a href="{% url 'editquiz' pathitem.id%}">{{pathitem.order}}. {{pathitem|verbose_name}}: {{pathitem.title}}</a> {%if pathitem.isPublishable == True%}
                                <i class="fas fa-check" style="color:green;"></i> {%endif%}

                                <button style="float: right;" type="button" onclick="window.location.href='{% url 'deletequiz' pathitem.id %}';" class="btn btn-pill btn-outline-default"><i class="far fa-trash-alt"></i></button>

                                {%endif%}

                            </li>

                            {% endfor %}
                    </ul>

                    <script src="https://unpkg.com/web-animations-js@2.3.1/web-animations.min.js"></script>
                    <script src="https://unpkg.com/hammerjs@2.0.8/hammer.min.js"></script>
                    <script src="https://unpkg.com/muuri@0.7.1/dist/muuri.min.js"></script>

                </div>

                <div class="col-sm-4">

                    {% if section.id %}

                    <br />

                    <div class="modal fade" id="resourceModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">New Resource</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">

                                    <div class="form-group">
                                        <input type="text" class="form-control" name="resourcename" placeholder="Resource Name">
                                    </div>
                                    <div class="form-group">
                                        <input type="file" class="form-control-file" name="resource">
                                    </div>

                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Close</button>
                                    <button type="submit" name="addresource" class="btn btn-outline-dark"><i class="fas fa-plus"></i> Add Resource</button>
                                </div>
                            </div>
                        </div>
                    </div>

                    <button type="button" class="btn btn-outline-dark btn-block" data-toggle="modal" data-target="#resourceModal" data-whatever="@getbootstrap"><i class="fas fa-plus"></i> Add Resource</button>

                    <ul class="list-group mt-4">
                        {% for resource in section.resource_set.all %}
                        <li class="list-group-item"><a target="_blank" href="{{resource.link.url}}">{{resource.name}}</a>

                            <button style="float: right;" type="button" onclick="window.location.href='{% url 'deleteresource' resource.id %}';" class="btn btn-outline-default"><i class="far fa-trash-alt"></i></button>

                        </li>
                        {% endfor %}

                    </ul>

                    <br /> {% endif %}

                    <button type="submit" name="save_section" id="save_section" class="btn btn-outline-dark btn-block"><i class="far fa-save"></i> Save</button>

                    {% if section.id %} {% if section.isPublishable == True %}

                    <button type="submit" name="submit_section" id="submit_section" class="btn btn-danger btn-block">Submit</button>

                    {%else%}

                    <button type="submit" name="save_exit_section" id="save_exit_section" class="btn btn-outline-dark btn-block">Save and Exit</button>

                    {% endif %}

                    <button style="float: right;" type="button" onclick="window.location.href='{% url 'deletesection' section.id %}';" class="btn btn-block btn-outline-dark" style="margin-bottom: 5px;"><i class="far fa-trash-alt"></i> Delete Section</button>

                    {% endif %}
                </div>
            </div>
        </div>
    </form>

    <script type="text/javascript">
        var grid = new Muuri('.grid', {
            dragEnabled: true,
            dragAxis: 'y'
        });

        document.getElementById("save_section").onclick = function() {
            sendLPOrder()
        };

        document.getElementById("submit_section").onclick = function() {
            sendLPOrder()
        };

        function sendLPOrder() {

            var lp_order = document.getElementById("lp-order");
            lp_order.value = grid.getItems().map(item => item.getElement().getAttribute('data-id'));
            lp_order.form.submit();

        }
    </script>

    <script type="text/javascript">
        document.getElementById("save_exit_section").onclick = function() {
            sendLPOrder()
        };
    </script>

</div>

{%endblock%}

ocial/ocial_project/topics/templates/topics/home.html
{% extends 'base.html' %} {% block content %} {% load staticfiles %}

<div class="container">

    <img style="width:100%;" id="home_image" src="{% static 'home_image.png' %}"> 
    {% include "../temp/topics_list.html" %}

    <div class="wrapper" style="text-align: center;">
        <button align="center" onclick="window.location.href = '{% url 'topics' %}';" class="btn btn-danger">Explore More Topics</button>
    </div>

</div>

{%endblock%}